### ISSUE TITLE
Add documentation explaining the purpose of the module

### ISSUE THREAD

**Issue by gajus** [chentsulin/webpack-target-electron-renderer#10]
It is not clear what is the reason for needing this plugin. I only stumbled across it by reading the source code of https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.development.js.

**Comment by Delapouite** [comment]
According to this code included in webpack itself : 
https://github.com/webpack/webpack/blob/5b5775f9e2fc73fea46629f2d6a3ed7a1f8424d3/lib/WebpackOptionsApply.js#L112-L149

and this doc : https://webpack.github.io/docs/configuration.html#target

My understanding is that this module is not needed anymore and `config.target = 'electron'` can be used instead which is much simpler.

**Comment by geowarin** [comment]
I think it's no longer needed if you're on webpack 2.0, where you have an `electron-renderer` [target](https://github.com/webpack/webpack/blob/5b5775f9e2fc73fea46629f2d6a3ed7a1f8424d3/lib/WebpackOptionsApply.js#L150) that seems to match what this package is doing.
I tried to switch the `config.target` to `electron` but it had the nasty side effect of disabling hot reloading.

**Comment by chentsulin** [comment]
Sure, this module is no longer needed when you using webpack 2.0, but target `electron-renderer` has not been merged into 1.x branch.
https://github.com/webpack/webpack/pull/1467

**Comment by chentsulin** [comment]
Added document for this:
https://github.com/chentsulin/webpack-target-electron-renderer#how-this-module-works
