### ISSUE TITLE
electron version 1.0

### ISSUE THREAD

**Issue by fdu-axiometrics** [chentsulin/webpack-target-electron-renderer#16]
Just updated electron to version 1.0 and the app won't start. 

I'm checking the electron code and it is the same as the one described in electron website.
So just checking with you, if the plugin support electron 1.0?

Thanks!

**Comment by chentsulin** [comment]
This plugins should support electron v1. But I recommend using webpack `target: 'electron-renderer'` just like https://github.com/chentsulin/electron-react-boilerplate/pull/220

And you can find discusses about Electron 1.0 at https://github.com/chentsulin/electron-react-boilerplate/issues/217
