### ISSUE TITLE
Electron 0.35.0 wrapped public API under 'electron' module

### ISSUE THREAD

**Issue by rbkreisberg** [chentsulin/webpack-target-electron-renderer#2]
I think this will just shorten the list of externals to 'electron', but I leave that to you to decide.

https://github.com/atom/electron/releases

**Comment by chentsulin** [comment]
Maybe we can wait until 0.35 docs ready:
http://electron.atom.io/docs/v0.35.0/

**Comment by rbkreisberg** [comment]
Hah.  I guess it sounds like I'm jumping the gun, but I was using these docs.

https://github.com/atom/electron/blob/master/docs/README.md

**Comment by chentsulin** [comment]
I will keep them until electron project officially remove them from global require. See #3

**Comment by rbkreisberg** [comment]
nice.  thanks for the update.
